### ISSUE TITLE
хули у тебя боксы летают

### ISSUE THREAD

**Issue by mr-nv** [XaRex1337/lovemachine_css#1]
вместо [этого](https://github.com/XaRex1337/lovemachine_css/blob/main/lovemachine/esp.h#L40) используй [это](https://github.com/mr-nv/interwebz/blob/master/CBaseEntity.h#L10)

**Comment by XaRex1337** [comment]
ахуеть, кому-то не похуй
спасибо, исправлю, пока делал бектрек доходил до этого и делал заметки, но руки уже не дошли, забил

**Comment by mr-nv** [comment]
если триггербот вдруг делать будешь спизди этот фикс чтоб голову нормально определяло https://github.com/mr-nv/interwebz/blob/master/CAimbot.cpp#L1015

**Comment by mr-nv** [comment]
https://github.com/XaRex1337/lovemachine_css/blob/main/lovemachine/backtrack.h#L78-L82
еще попробуй все это закомментить (мне впадлу запускать ксс), если бектрек все так же нормально работает то не добавляй
у меня когда я в 2019 бектрек делал, противник которого я бектрекал тпхался обратно либо у него анимация ходьбы ломалась, не прикольно короче

**Comment by XaRex1337** [comment]
> если триггербот вдруг делать будешь спизди этот фикс чтоб голову нормально определяло https://github.com/mr-nv/interwebz/blob/master/CAimbot.cpp#L1015

уже есть триггер, дак вот оно как фиксится, во прикол, спасибо

**Comment by XaRex1337** [comment]
> https://github.com/XaRex1337/lovemachine_css/blob/main/lovemachine/backtrack.h#L78-L82 еще попробуй все это закомментить (мне впадлу запускать ксс), если бектрек все так же нормально работает то не добавляй у меня когда я в 2019 бектрек делал, противник которого я бектрекал тпхался обратно либо у него анимация ходьбы ломалась, не прикольно короче

чекну, но все должно продолжить работать, не замечал поломок

**Comment by XaRex1337** [comment]
> если триггербот вдруг делать будешь спизди этот фикс чтоб голову нормально определяло https://github.com/mr-nv/interwebz/blob/master/CAimbot.cpp#L1015

все, кроме этого, исправил, скорее всего, там че-то устарело, виз чек => traceray перестает работать стабильно и срабатывает адекватно только на движущихся, пытался использовать цикл в разных местах и в уже имеющемся цикле пристроить - без толку

**Comment by mr-nv** [comment]
да там оффсеты устарели, я посмотрел и обновил https://github.com/mr-nv/interwebz/commit/3d01fbcc7bbcc828bddfc14eee50eeb9875ffa3a

**Comment by XaRex1337** [comment]
не, та же херь

**Comment by XaRex1337** [comment]
но спасибо за помощь

**Comment by XaRex1337** [comment]
наполовину закрыто
