### ISSUE TITLE
pch file missing

### ISSUE THREAD

**Issue by sndcode** [XaRex1337/lovemachine_css#2]
compiler tells me pch.h is missing precompiled headers error

**Comment by XaRex1337** [comment]
go to your settings of project and find "require precompiled files" or smth like that and turn it off

**Comment by XaRex1337** [comment]
did you fix it?

**Comment by sndcode** [comment]
This does not work since it now throws thousands of syntax errors on the compiler 
Do you use VS 2022 ?

**Comment by XaRex1337** [comment]
> Do you use VS 2022 ?
yes i do

> throws thousands of syntax errors

screenshot or smth?

**Comment by XaRex1337** [comment]
> Do you use VS 2022 ?

yes i do
> throws thousands of syntax errors

screenshot or smth?

**Comment by sndcode** [comment]
https://imgur.com/a/4TjdDJ5

**Comment by sndcode** [comment]
it says : 4 not found external dependencies : 
following garbage..

https://learn.microsoft.com/de-de/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?f1url=%3FappId%3DDev16IDEF1%26l%3DDE-DE%26k%3Dk(LNK2019)%26rd%3Dtrue&view=msvc-170

**Comment by XaRex1337** [comment]
build as release x86

**Comment by XaRex1337** [comment]
issue closed
