### ISSUE TITLE
Ошибка E0020

### ISSUE THREAD

**Issue by weaponsmg1** [XaRex1337/lovemachine_css#4]
Я решил написать чит на базе етого и в Visual Studio 2 ошибки индефикатора 
LPD3DXFONT
D3DXCreateFontA

**Comment by XaRex1337** [comment]
установи directx sdk june 2010
проверь чтобы билд был release x86

**Comment by weaponsmg1** [comment]
а Visual Studio какой версии нада 2010 2013 2015 2017 2019 2022 ?

**Comment by XaRex1337** [comment]
> а Visual Studio какой версии нада 2010 2013 2015 2017 2019 2022 ?

любой, чит на старых стандартах написан

**Comment by weaponsmg1** [comment]
можеш дать силлку на directx sdk june 2010 просто откудова сейчас скачуваю при установки ошибки

**Comment by XaRex1337** [comment]
> можеш дать силлку на directx sdk june 2010 просто откудова сейчас скачуваю при установки ошибки

https://www.microsoft.com/en-US/download/details.aspx?id=6812

**Comment by XaRex1337** [comment]
закрыто
