### ISSUE TITLE
Yo what this is Mean?

### ISSUE THREAD

**Issue by RustOsprey55681** [XaRex1337/lovemachine_css#6]
https://www.virustotal.com/gui/file/04a43a5c935688730755f2ff2d1610f1d3debf4d8e9ebdbe11b354b8487eaf4c/detection/f-04a43a5c935688730755f2ff2d1610f1d3debf4d8e9ebdbe11b354b8487eaf4c-1689816233

is that really Virus????
give me proof

**Comment by XaRex1337** [comment]
look at source, compile it yourself or just check both (compiled and uploaded) dll sha256

**Comment by RustOsprey55681** [comment]
how do I compile it? I don't have Visual Studio. they installing forever

**Comment by XaRex1337** [comment]
> how do I compile it? I don't have Visual Studio. they installing forever

then I won't proof you anything. project is open source and you can check everything yourself, I don't give a shit

**Comment by XaRex1337** [comment]
it's closed i think

**Comment by RustOsprey55681** [comment]
> > how do I compile it? I don't have Visual Studio. they installing forever
> 
> then I won't proof you anything. project is open source and you can check everything yourself, I don't give a shit

well, I can't coding. but anyway, thanks for replying :)

**Comment by RustOsprey55681** [comment]
> > how do I compile it? I don't have Visual Studio. they installing forever
> 
> then I won't proof you anything. project is open source and you can check everything yourself, I don't give a shit

well, I can't coding. but anyway, thanks for replying :)
